### ISSUE TITLE
.gitignore sufficient?

### ISSUE THREAD

**Issue by kelecss** [UniLuFS2020-ReplicationSeminar/CE2_Alluri_Hess_Lengwiler_#1]
I have created a .gitignore file (see below for url) that contains the in my opinion most likely extensions of our future data. Please either output the original or processed data in one of the formates mentioned in the readme.gitignore file or alternatively add the extension to the readme.gitignore file.

I'd also appreciate it when you could copy that you have received the information above so that I can close the issue afterwards.

[readme.gitignore](https://github.com/UniLuFS2020-ReplicationSeminar/CE2_Alluri_Hess_Lengwiler_/blob/75eba53f7098606cf15884e2295326184ca8c286/readme.gitignore)

**Comment by silvanhess** [comment]
Can you create one .gitignore file an one readme file instead of a readme.gitignore? It is a bit confusing.

Sent from Android device

Am 29.04.2024 21:18 schrieb kelecss ***@***.***>:

Assigned #1<https://github.com/UniLuFS2020-ReplicationSeminar/CE2_Alluri_Hess_Lengwiler_/issues/1> to @kutskey<https://github.com/kutskey>.

**Comment by silvanhess** [comment]
The readme file usually contains the filestructure of the project

Sent from Android device

Am 29.04.2024 22:18 schrieb Hess Silvan ***@***.***>:
Can you create one .gitignore file an one readme file instead of a readme.gitignore? It is a bit confusing.

Sent from Android device

Am 29.04.2024 21:18 schrieb kelecss ***@***.***>:

Assigned #1<https://github.com/UniLuFS2020-ReplicationSeminar/CE2_Alluri_Hess_Lengwiler_/issues/1> to @kutskey<https://github.com/kutskey>.

**Comment by AVishal9** [comment]
I added the "data_original" in the gitignore document,
Maybe should have done that before pushing it (possibly same like last time) - Not sure.
Also added  .Renviron  in gitignore and created a .Renviron text file
 in my project directory (steps on script 01)
This file is to store your Guardian API key so that you have it saved and are not pushing it to github

**Comment by kelecss** [comment]
Since there now already was a .gitignore file from Vishal, I added the content from the readme.gitignore file to the .gitignore file and deleted my file.
